const images = {
  logo: require("../Assets/Images/olilitLogo.png"),
  legalSync: require("../Assets/Images/legalsynq.png"),
  rightArrow: require("../Assets/Images/rightArrow.png"),
  leftArrow: require("../Assets/Images/leftArrow.png"),
  filterIcon: require("../Assets/Images/filterIcon.png"),
  searchIcon: require("../Assets/Images/searchIcon.png"),
  checkIcon: require ("../Assets/Images/checkIcon.png"),
  exIcon: require ("../Assets/Images/exIcon.png"),
  bag: require("../Assets/Images/bag.png"),
  contacts: require("../Assets/Images/contacts.png"),
  user: require("../Assets/Images/user.png"),
  company: require("../Assets/Images/company.png"),
  personIcon: require("../Assets/Images/personIcon.png"),
  calendarIcon: require("../Assets/Images/calendarIcon.png"),
  calendar2Icon: require("../Assets/Images/calendar2Icon.png"),
  locationIcon: require("../Assets/Images/locationIcon.png"),
  phoneIcon: require("../Assets/Images/phoneIcon.png"),
  gearPersonIcon: require("../Assets/Images/gearPersonIcon.png"),
  girlIcon: require("../Assets/Images/girlIcon.png"),
  planeIcon: require("../Assets/Images/planeIcon.png"),
  Notif: require("../Assets/Images/Notification.png"),
  Gcheck: require("../Assets/Images/gcheck.png"),
  check: require("../Assets/Images/check.png"),
  arrowButton: require("../Assets/Images/arrowButton.png"),
  phone2Icon: require("../Assets/Images/phone2Icon.png"),
  atIcon: require("../Assets/Images/atIcon.png"),
  settingsIcon: require("../Assets/Images/settingsIcon.png")
};

export default images;  